### ISSUE TITLE
Source distribution on PyPI

### ISSUE THREAD

**Issue by ocefpaf** [SamLau95/nbinteract#106] opened 2019-05-14 15:34 UTC
Please consider uploading the source distribution to PyPI instead of just wheels. PyPI is a canonical place for sdists and very few tools/third party python packagers (debian, fedora, etc) get the source from GitHub.

**Comment by moorepants** [comment] 2020-02-06 15:39
Duplicate of #95

**Closed** 2020-05-05 16:54 UTC
